{{- if .Values.domain }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-grafana
  namespace: observability
  annotations:
    kubernetes.io/ingress.class: "nginx" 
    cert-manager.io/issuer: "letsencrypt-ci"
spec:
  tls:
  - hosts:
    - grafana.{{ .Values.domain }}
    secretName: nginx-grafana-tls
  rules:
  - host: grafana.{{ .Values.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: observability-grafana
            port:
                number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-argocd
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: "nginx" 
    cert-manager.io/issuer: "letsencrypt-ci"
spec:
  tls:
  - hosts:
    - argocd.{{ .Values.domain }}
    secretName: nginx-argocd-tls
  rules:
  - host: argocd.{{ .Values.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port: 
                number: 80
{{- end }}