apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-ip-space
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  addresses:
  - {{ .Values.metallb.addresspool}}