{{- if .Values.logging.enable }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 0.69.0
    chart: loki-distributed
    helm:
      parameters:
      - name: gateway.enabled
        value: "true"
      - name: querier.persistence.storageClass
        value: "{{ .Values.observability.storageClass }}"
      - name: compactor.persistence.storageClass
        value: "{{ .Values.observability.storageClass }}"
      - name: ingestor.persistence.storageClass
        value: "{{ .Values.observability.storageClass }}"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: observability
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}