apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-feature-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: open-feature-operator-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: ofo
    repoURL: https://open-feature.github.io/open-feature-operator/
    targetRevision: v0.2.20
  syncPolicy:
    automated: {}