{{- if .Values.komodor.enable }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: komodor
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
 project: default
 source:
  repoURL: 'https://github.com/komodorio/helm-charts'
  path: charts/k8s-watcher
  targetRevision: HEAD
  helm:
    parameters:
        - name: watcher.clustername
          value: {{ .Values.komodor.clustername }}
        - name: watcher.actions.basic
          value: 'true'
        - name: watcher.actions.advanced
          value: 'true'
        - name: apiKey
          value: {{ .Values.komodor.key }}
 destination:
  server: 'https://kubernetes.default.svc'
  namespace: komodor
 syncPolicy:
  automated: {}
  syncOptions:
    - CreateNamespace=true
{{- end }}
